# Generated by Django 3.0.6 on 2020-05-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Passport Number'),
        ),
    ]
