# Generated by Django 3.0.5 on 2020-04-28 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='CarCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('second_name', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('work_experience', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('price_per_hour_usd', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price per hours USD')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Description')),
                ('car_took_counter', models.IntegerField(default=0, verbose_name='Car was taken times')),
                ('is_driver_available', models.BooleanField(default=False, verbose_name='Is driver available')),
                ('is_car_available', models.BooleanField(default=False, verbose_name='Is car available')),
                ('when_will_be_available', models.DateTimeField(verbose_name='When car will be available')),
                ('last_took_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last took date')),
                ('car_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.CarClass', verbose_name='Car class')),
                ('car_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.CarCondition', verbose_name='Car condition')),
                ('car_mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.CarMark', verbose_name='Car mark')),
            ],
        ),
    ]
