# Generated by Django 3.0.5 on 2020-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='layout',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Layout'),
        ),
    ]
