# Generated by Django 3.0.5 on 2020-05-02 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_car_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='when_will_be_available',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When car will be available'),
        ),
    ]
