# Generated by Django 3.0.6 on 2020-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_auto_20200502_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_driver_available',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='car_default.jpg', upload_to='car_pics', verbose_name='Car image'),
        ),
        migrations.AlterField(
            model_name='carcondition',
            name='condition',
            field=models.CharField(max_length=100, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='second_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='work_experience',
            field=models.FloatField(verbose_name='Work Experience'),
        ),
    ]
