# Generated by Django 3.0.6 on 2020-05-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20200516_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_hours',
            field=models.IntegerField(default=0, verbose_name='Total hours'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total Price'),
        ),
    ]
