# Generated by Django 3.0.6 on 2020-05-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_auto_20200516_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(),
        ),
    ]
