# Generated by Django 3.0.6 on 2020-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_auto_20200519_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_description',
            field=models.TextField(default='Reason of cancellation:', max_length=500, verbose_name='Cancel description'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(default=True, verbose_name='Is Pending'),
        ),
    ]
