# Generated by Django 3.0.6 on 2020-05-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_auto_20200520_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_took_counter',
        ),
        migrations.RemoveField(
            model_name='car',
            name='last_took_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='when_will_be_available',
        ),
    ]
